### PR TITLE
Add Pretty::RAST

### PR DESCRIPTION
**Pull request by alabamenhu**
Add this module to the ecosystem

- [X] I **agree** to the usage of the META file as listed [here](https://github.com/Raku/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by JJ** [comment]
Can you please check the error? Looks like a real one.

**Comment by alabamenhu** [comment]
This may be because it requires the RakuAST branch. I'm not sure how we should best handle that, actually.

**Comment by vrurg** [comment]
@alabamenhu Best if you skip the tests on non-RakuAST build. At the module level I'd recommend to check for this too and print a meaningful error.

BTW, consider publishing with `fez`. It is the recommended ecosystem for now.

**Comment by 2colours** [comment]
@alabamenhu what is the current state of this PR? Either it could be rebased to main, or just closed in favor of another submission method.

**Comment by JJ** [comment]
It's probably best if we actually close this to new submissions. Even if it's easier, Travis no longer works and we prefer the zef ecosystem anyway.

**Comment by alabamenhu** [comment]
I'm totally fine with that — plus I need to update this anyways so … off to fez :-)

**Pull request closed without merging**
