### PR TITLE
Release last working version to the ecosystem

### PR DESCRIPTION
**Pull request by JJ**
- [X] I **agree** to the usage of the META file as listed [here](https://github.com/Raku/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by Altai-man** [comment]
This is not a last version, last version is 0.8, no? If it does not work properly, we should fix it and move on.

**Comment by JJ** [comment]
It's the last working version. Anyway, the META6.json is not correct, since it does not actually include the source to *that* specific tag.

**Comment by Altai-man** [comment]
>It's the last working version

Please, specify what you are doing exactly (what commands are run, what versions of packages do you have), what is shown and how it should behave. Then I will do my best with fixing the bug on master, version bump and it's solved. Downgrading is not a proper solution.

**Comment by JJ** [comment]
OK, I'm closing this. Not easy to figure out how to specify source-url anyway.

**Pull request closed without merging**
