### PR TITLE
Re-add Pakku to the Ecosystem

### PR DESCRIPTION
**Pull request by hythm7**
- [X] I **agree** to the usage of the META file as listed [here](https://github.com/Raku/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Perhaps I've hit the merge button a bit too early. Can you check the log here? https://travis-ci.com/github/Raku/ecosystem/builds/191220344#L173

**Comment by hythm7** [comment]
> Perhaps I've hit the merge button a bit too early. Can you check the log here? https://travis-ci.com/github/Raku/ecosystem/builds/191220344#L177

checking...

**Comment by JJ** [comment]
Yes, it was probably too early. There's a good amount of errors, although none of them are specific to this distribution. What I generally do is to try and find what's the matter there, to see if there's something that needs to be patched. You can still do that.

**Comment by JJ** [comment]
I think that the problem is that NativeLibs is version-locked, and 0.0.7 is no longer available. I can try and do a PR for that, but I'm not sure that's the only error here. If you hadn't merged, I could have relaunched the test to see what was temporary and what wasn't

**Comment by AlexDaniel** [comment]
@JJ you can still relaunch it: https://travis-ci.com/github/Raku/ecosystem/builds/191221577

**Comment by JJ** [comment]
Yes, I can and it will fail to fetch the code. Never mind.
The problem with NativeLibs is in [libcurl](https://github.com/CurtTilmes/raku-libcurl), it was patched, but not released. So maybe we can ask for a new release here.
The others, I don't really know.

**Comment by JJ** [comment]
I think also that `ver<pupa>` in the dependencies is incorrect. I would need to check it, but ver needs to be of the form x.y.z and if it does not, it goes to 0... which it's then unable to download.
I can't figure out the Log::Async part, though.

**Comment by hythm7** [comment]
I don't have explanation for the `Log::Async` error, but it looks like `Log::Async` need to be installed before testing the module, but it's already listed in the module `depends` section so I don't know if the dependencies should be installed before testing a module with Zef. (and if so I'd imagine other modules would give similar errors as well). may be @ugexe have a sugesstion how to fix this?

@ugexe I'm getting `[Pakku] Could not find Log::Async in:` error when trying to test Pakku:
to reproduce I do: 
```

hythm@galaxy$ git clone https://github.com/hythm7/Pakku.git
hythm@galaxy$ zef test ./Pakku/
===> Testing: Pakku:ver<pupa>:auth<github:hythm7>
[Pakku] ===SORRY!=== Error while compiling /tmp/delme/Pakku/t/00-basic.rakutest
[Pakku] ===SORRY!=== Error while compiling /tmp/delme/Pakku/lib/Pakku.rakumod (Pakku)
[Pakku] ===SORRY!=== Error while compiling /tmp/delme/Pakku/lib/Pakku/Log.rakumod (Pakku::Log)
[Pakku] Could not find Log::Async in:
[Pakku]     file#/tmp/delme/Pakku
[Pakku]     inst#/home/hythm/.raku
....
....
````

**Comment by hythm7** [comment]
I dont see the full log on the travis links above. but that error `Could not find Log::Async in:` means dependencies is not installed on the machine testing the module.

**Comment by AlexDaniel** [comment]
```
Cloning into '/tmp/Pakku'...

remote: Enumerating objects: 107, done.

remote: Counting objects: 100% (107/107), done.

remote: Compressing objects: 100% (71/71), done.

remote: Total 110 (delta 40), reused 97 (delta 31), pack-reused 3

Receiving objects: 100% (110/110), 671.87 KiB | 12.68 MiB/s, done.

Resolving deltas: 100% (40/40), done.

    ok 1 - Downloading https://raw.githubusercontent.com/hythm7/Pakku/main/META6.json

        ok 1 - have a META file

        ok 2 - META parses okay

        ok 3 - have all required entries

        ok 4 - 'provides' looks sane

        ok 5 - Optional 'authors' and not 'author'

        ok 6 - License is correct

        ok 7 - name has a '::' rather than a hyphen (if this is intentional please pass :relaxed-name to meta-ok)

        ok 8 - no 'v' in version strings (meta-version greater than 0)

        ok 9 - version is present and doesn't have an asterisk

        ok 10 - have usable source

        1..10

    ok 2 - Project META file is good

===> Searching for missing dependencies: File::Temp, Terminal::ANSIColor, Log::Async, URL, LibCurl, Libarchive, Pakku::Spec:ver<pupa>:auth<github:hythm7>, Pakku::Meta:ver<pupa>:auth<github:hythm7>, Pakku::RecMan::Client:ver<pupa>:auth<github:hythm7>

===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json

===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json

===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json

===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json

===> Searching for missing dependencies: NativeLibs:ver<0.0.7>:auth<github:salortiz>, Test::When, Archive::Libarchive::Raw, Archive::Libarchive::Constants, NativeHelpers::Callback, Number::Bytes::Human, BitEnum, File::Directory::Tree

===> Failed to find dependencies: NativeLibs:ver<0.0.7>:auth<github:salortiz>

Failed to resolve some missing dependencies

    not ok 3 - Able to install deps

    # Failed test 'Able to install deps'

    # at ./.travis/testpackagemeta.p6 line 88

===> Testing: Pakku:ver<pupa>:auth<github:hythm7>

[Pakku] ===SORRY!=== Error while compiling /tmp/Pakku/t/00-basic.rakutest

[Pakku] ===SORRY!=== Error while compiling /tmp/Pakku/lib/Pakku.rakumod (Pakku)

[Pakku] ===SORRY!=== Error while compiling /tmp/Pakku/lib/Pakku/Log.rakumod (Pakku::Log)

[Pakku] Could not find Log::Async in:

[Pakku]     file#/tmp/Pakku

[Pakku]     inst#/home/raku/.raku

[Pakku]     inst#/home/raku/.raku/share/perl6/site

[Pakku]     inst#/home/raku/.raku/share/perl6/vendor

[Pakku]     inst#/home/raku/.raku/share/perl6/core

[Pakku]     ap#

[Pakku]     nqp#

[Pakku]     perl5#

[Pakku] Please note that a 'META6.json' file was found in '.', of which the 'provides' section was used to determine if a dependency is available or not.  Perhaps you need to add 'Log::Async' in the <provides> section of that file?  Or need to specify a directory that does *not* have a 'META6.json' file?

[Pakku] at /tmp/Pakku/lib/Pakku/Log.rakumod (Pakku::Log):1

[Pakku] at /tmp/Pakku/lib/Pakku.rakumod (Pakku):1

[Pakku] at /tmp/Pakku/t/00-basic.rakutest:3

[Pakku] ===SORRY!=== Error while compiling /tmp/Pakku/t/01-cmd.rakutest

[Pakku] Could not find Pakku::Spec in:

[Pakku]     file#/tmp/Pakku

[Pakku]     inst#/home/raku/.raku

[Pakku]     inst#/home/raku/.raku/share/perl6/site

[Pakku]     inst#/home/raku/.raku/share/perl6/vendor

[Pakku]     inst#/home/raku/.raku/share/perl6/core

[Pakku]     ap#

[Pakku]     nqp#

[Pakku]     perl5#

[Pakku] Please note that a 'META6.json' file was found in '.', of which the 'provides' section was used to determine if a dependency is available or not.  Perhaps you need to add 'Pakku::Spec' in the <provides> section of that file?  Or need to specify a directory that does *not* have a 'META6.json' file?

[Pakku] at /tmp/Pakku/t/01-cmd.rakutest:4

[Pakku] ===SORRY!=== Error while compiling /tmp/Pakku/t/03-dist.rakutest

[Pakku] Could not find Pakku::Meta in:

[Pakku]     file#/tmp/Pakku

[Pakku]     inst#/home/raku/.raku

[Pakku]     inst#/home/raku/.raku/share/perl6/site

[Pakku]     inst#/home/raku/.raku/share/perl6/vendor

[Pakku]     inst#/home/raku/.raku/share/perl6/core

[Pakku]     ap#

[Pakku]     nqp#

[Pakku]     perl5#

[Pakku] Please note that a 'META6.json' file was found in '.', of which the 'provides' section was used to determine if a dependency is available or not.  Perhaps you need to add 'Pakku::Meta' in the <provides> section of that file?  Or need to specify a directory that does *not* have a 'META6.json' file?

[Pakku] at /tmp/Pakku/t/03-dist.rakutest:5

===> Testing [FAIL]: Pakku:ver<pupa>:auth<github:hythm7>

Aborting due to test failure: Pakku:ver<pupa>:auth<github:hythm7> (use --force-test to override)

    not ok 4 - Package tests pass

    # Failed test 'Package tests pass'

    # at ./.travis/testpackagemeta.p6 line 90

    1..4

    # You failed 2 tests of 4

not ok 1 - Checking correctness of https://raw.githubusercontent.com/hythm7/Pakku/main/META6.json

# Failed test 'Checking correctness of https://raw.githubusercontent.com/hythm7/Pakku/main/META6.json'

# at ./.travis/testpackagemeta.p6 line 44

The following urls failed:

https://raw.githubusercontent.com/hythm7/Pakku/main/META6.json

# You failed 1 test of 1

The command "docker run -e TRAVIS_COMMIT_RANGE="HEAD^1...HEAD" -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/raku-test-ecosystem" exited with 1.

Done. Your build exited with 1.
```

**Comment by hythm7** [comment]
from travis test script:
```raku

my $zef = run "zef", "install", "--depsonly", "--/build", ".";
ok $zef.exitcode eq 0, "Able to install deps";
$zef = run "zef", "test", ".";
ok $zef.exitcode eq 0, "Package tests pass";
```

From what I understand from Travis test script, the script tries to install the dependencies,and we see the `NativeLibs` error, and due to this error `Zef` abort the process, and no dependencies installed. Then travis script proceed  with testing the module (  it shouldn't proceed because the previous step didn't complete successfully), and when zef start testing the module we see the Log::Async depenedncy error, because it wasn't installed in the previous step.

That is my guess but we will know when `NativeLibs` issue is fixed.

**Pull request merged**
