### PR TITLE
Update DDT and its dependency License::Software

### PR DESCRIPTION
**Pull request by kalkin**
This fixes kalkin/Ddt/issues/10

### CODE REVIEW

**Comment by JJ** [comment]
There seems to be a problem with tests, can you please check?

**Comment by kalkin** [comment]
@JJ Actually a dependency `Pluggable` has broken tests and so it can't be installed, which breaks my tests. :-/

**Comment by JJ** [comment]
Can you try and patch it via PR?

**Comment by patrickbkr** [comment]
I have created a PR to address this: [tony-o/perl6-pluggable#15](https://github.com/tony-o/perl6-pluggable/pull/15). It's waiting for the merge.

**Comment by JJ** [comment]
Thanks, Patrick.

**Comment by patrickbkr** [comment]
The fix for perl6-pluggable is now merged. So this should be able to move forward. @kalkin

**Comment by JJ** [comment]
There's a conflict now. I sorted alphabetically the file, so I guess it's my fault. I'll try to solve it.

**Comment by JJ** [comment]
I'll need to sort it out locally. I'll note what's been added, close this and add it back. Also, I need to see if the CI works properly with non-master submissions. Is it OK if I do that for everyone?

**Comment by patrickbkr** [comment]
@JJ Fine by me!

**Comment by patrickbkr** [comment]
@JJ Any updates on this?

**Comment by JJ** [comment]
> @JJ Any updates on this?

Just forgot, sorry. Will do tomorrow

**Comment by JJ** [comment]
I'm going to leave it open, while I'm working on it. This fails now with this error:

```
[License::Software]     # github source https://github.com/kalkin/License-Software needs to end in .git
[License::Software] # Failed test 'get-all() found Licenses'
[License::Software] # at t/01-basic.t line 8
[License::Software] # You failed 1 test of 1
[License::Software] Can not find license alias 'gplv3'
[License::Software]   in sub license at /tmp/License__Software/lib/License/Software.pm6 (License::Software) line 172
[License::Software] # Failed test at t/10-gplv3.t line 8
[License::Software] Method 'aliases' must be implemented by License::Software::Abstract because it is required by roles: .
[License::Software]   in block <unit> at t/10-gplv3.t line 9
[License::Software] # You planned 10 tests, but ran 1
[License::Software] # You failed 1 test of 1
[License::Software] Can not find license alias 'apache'
[License::Software]   in sub license at /tmp/License__Software/lib/License/Software.pm6 (License::Software) line 172
[License::Software] # Failed test at t/11-Apache2.t line 9
[License::Software] Method 'aliases' must be implemented by License::Software::Abstract because it is required by roles: .
[License::Software]   in block <unit> at t/11-Apache2.t line 10
[License::Software] # You planned 13 tests, but ran 1
[License::Software] # You failed 1 test of 1
[License::Software] Can not find license alias 'lgplv3'
[License::Software]   in sub license at /tmp/License__Software/lib/License/Software.pm6 (License::Software) line 172
[License::Software] # Failed test at t/12-LGPLv3.t line 8
[License::Software] Method 'aliases' must be implemented by License::Software::Abstract because it is required by roles: .
[License::Software]   in block <unit> at t/12-LGPLv3.t line 9
[License::Software] # You planned 8 tests, but ran 1
[License::Software] # You failed 1 test of 1
[License::Software] Can not find license alias 'agplv3'
[License::Software]   in sub license at /tmp/License__Software/lib/License/Software.pm6 (License::Software) line 172
[License::Software] # Failed test at t/13-AGPLv3.t line 7
[License::Software] Method 'aliases' must be implemented by License::Software::Abstract because it is required by roles: .
[License::Software]   in block <unit> at t/13-AGPLv3.t line 8
[License::Software] # You planned 11 tests, but ran 1
[License::Software] # You failed 1 test of 1
[License::Software] Can not find license alias 'artistic'
[License::Software]   in sub license at /tmp/License__Software/lib/License/Software.pm6 (License::Software) line 172
[License::Software] # Failed test at t/14-Artistic2.t line 7
[License::Software] Method 'aliases' must be implemented by License::Software::Abstract because it is required by roles: .
[License::Software]   in block <unit> at t/14-Artistic2.t line 8
[License::Software] # You planned 8 tests, but ran 1
[License::Software] # You failed 1 test of 1
===> Testing [FAIL]: License::Software:ver<0.3.0>:auth<kalkin>
Aborting due to test failure: License::Software:ver<0.3.0>:auth<kalkin> (use --force-test to override)
    not ok 4 - Package tests pass
    # Failed test 'Package tests pass'
    # at .travis/testpackagemeta.p6 line 85
    1..4
    # You failed 1 test of 4
not ok 1 - Checking correctness of https://raw.githubusercontent.com/kalkin/License-Software/v0.3.0/META6.json
# Failed test 'Checking correctness of https://raw.githubusercontent.com/kalkin/License-Software/v0.3.0/META6.json'
# at .travis/testpackagemeta.p6 line 44

The following urls failed:
https://raw.githubusercontent.com/kalkin/License-Software/v0.3.0/META6.json
# You failed 1 test of 1
```

But I suspect it's because it's not downloading the release, but the current content. Let me check anyway.

**Comment by JJ** [comment]
Additionally, the source-url in the current META6.json points to master, which I have checked locally, it's still failing. That's just as well, since the test script is not prepared for non-git URIs, and I'm not totally sure we can either specify a release tag in source-url or actually use it. I'm going to work on the second module meanwhile, but it would also help if the tests would work. I've checked out locally the v0.3.0 tag, and it also fails.

**Comment by JJ** [comment]
My impression with this is that this sentence
```
 return eager plugins('License', :plugins-namespace('Software')) ==> grep( {
       $_ ~~ License::Software::Abstract &&
       $_.^name !~~ 'License::Software::Abstract'
   })
```

(in get-all) is behaving in a different way as it should be expected. It keeps returning 
```
X::NoSuchSymbol(SETTING::src/core.c/Exception.pm6 62 throw)
X::NoSuchSymbol(SETTING::src/core.c/Exception.pm6 62 throw)
```
and I'm not sure why. I'll dig into Pluggable to see if this is a case of a LTA error message, but I'm really a bit out of my depth here.

**Comment by JJ** [comment]
Moreover, calling the test directly or using zef test . returns different results, and I'm really flabbergasted as to why. What I kind of found out is that

```
ok $license = license('apache').new("FooBar", $pair.Hash );
```

Fails to find a suitable `new` `multi` and thus returns Nil, which makes the others fail.

Boils down to: there are several new errors in `License::Software` that are not only test errors, but seem to go deeper into its design.

**Comment by JJ** [comment]
Just to be clear, this is not to be merged, but is left as a placeholder for what we have done to actually incorporate these new versions to the ecosystem.

**Comment by JJ** [comment]
When the PR above is merged (and a new release done) I think we're halfway there.

**Comment by JJ** [comment]
Tell me when it's ready for review and merging.

**Comment by kalkin** [comment]
@JJ I think I need to separate it into two PRs. First one for License::Software and the second one for Ddt.

**Comment by JJ** [comment]
Checking it now

**Comment by kalkin** [comment]
Ok this is one I can reproduce locally, but I can't explain. This error seems even to occur with older versions of Ddt.

**Comment by JJ** [comment]
Tough one, yes... Probably it's the best to raise an issue...

**Pull request merged**
