### PR TITLE
Add my Shell::DSL module to the list

### PR DESCRIPTION
**Pull request by kjkuan**
Thanks!

- [X] I **agree** to the usage of the META file as listed [here](https://github.com/Raku/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by kjkuan** [comment]
hmm, I might have to fork and publish my own Fcntl module...

**Comment by JJ** [comment]
> hmm, I might have to fork and publish my own Fcntl module...

Can you maybe offer a PR?

**Comment by kjkuan** [comment]
@JJ There's already a PR to fix the original Fcntl module. Let me contact the author to see if he/she can merge it and release a new version of the module first.

**Comment by kjkuan** [comment]
See https://github.com/manchicken/perl6-Fcntl/pull/3

**Comment by JJ** [comment]
You can create an "auth" version and release it too. Probably the fastest thing.

**Comment by kjkuan** [comment]
so I forked the Fcntl module with `:auth<github:kjkuan>` and added it as a dependency of this module.
I think the build failed now because the forked module is not available in the ecosystem yet? Perhaps, I have to create a separate PR for the fork and merge it first before this one can pass the CI?

**Comment by JJ** [comment]
El lun., 17 ago. 2020 a las 2:20, Jack Kuan (<notifications@github.com>)
escribió:

> so I forked the Fcntl module with :auth<github:kjkuan> and added it as a
> dependency of this module.
> I think the build failed now because the forked module is not available in
> the ecosystem yet? Perhaps, I have to create a separate PR for the fork and
> merge it first before this one can pass the CI?
>

Yes, that would be the right way of doing this. Since this one will need to
pass the tests anyway, probably the best thing is that you delete this
line, use this same PR for the new distribution, and then create a new PR
for Shell::DSL when that one is merged.

**Comment by JJ** [comment]
We'll wait a while to check again here.

**Comment by kjkuan** [comment]
I was able to install my version of `Fcntl` module from the ecosystem earlier. Could you trigger a rebuild? @JJ

**Comment by manchicken** [comment]
I'm sorry, @JJ and @kjkuan, I was stupid busy this week.

**Comment by kjkuan** [comment]
@manchicken Thanks for following up. Yeah, if you could cut a release and submit it to the ecosystem that would be great! Then I'll make my module depend on yours instead of my fork, and then I can remove my fork from the ecosystem. Thanks again!

**Comment by manchicken** [comment]
Sure. It's been a while but I'll try to do that now.

**Comment by manchicken** [comment]
I believe I just uploaded it, please let me know if you don't see it.

**Pull request merged**
