### PR TITLE
new module 'Hematite::Middleware::Session'

### PR DESCRIPTION
**Pull request by whity**
- [X] I **agree** to the usage of the META file as listed [here](https://github.com/Raku/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by JJ** [comment]
Can you please check the error log, correct and resubmit? It's complaining about the name (see test #7)

**Comment by whity** [comment]
Thanks, it's fixed.

**Comment by JJ** [comment]
Can you please check again? Now there seems to be a different problem.

**Comment by whity** [comment]
I'm sorry, was referring to the wrong module in META, should be fixed

**Comment by JJ** [comment]
Since there's an external dependency, it can't properly be tested. However, I wasn't able to install it locally due to a different dependency, HTTP::Parser, failing. I'll try and deal with that.

**Comment by whity** [comment]
Ok, thanks

**Pull request merged**
