### PR TITLE
Add new Bio module. See https://github.com/schmidt73/Bio.

### PR DESCRIPTION
**Pull request by schmidt73**
- [X] I **agree** to the usage of the META file as listed [here](https://github.com/Raku/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by schmidt73** [comment]
I missed the source-url element in the JSON file. I fixed it here.

**Comment by skaji** [comment]
You don't have a license field listed in META6.json

**Comment by schmidt73** [comment]
I didn't think I needed one? I just used the default Perl6 license.

**Comment by skaji** [comment]
>  I have a license field listed in my META file that is one of https://spdx.org/licenses

Why did you check this checkbox?

**Comment by schmidt73** [comment]
I made an error. Sorry. I fixed it.

**Pull request merged**
