### PR TITLE
Add new modules

### PR DESCRIPTION
**Pull request by hythm7**
- [X] I **agree** to the usage of the META file as listed [here](https://github.com/Raku/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by hythm7** [comment]
Looks like the build has failed because of missing dependencies, All these modules depend on `Pakku::Spec`, which is a new module and not in the ecosystem yet. Do I need to PR each module separately?

**Comment by JJ** [comment]
> Looks like the build has failed because of missing dependencies, All these modules depend on `Pakku::Spec`, which is a new module and not in the ecosystem yet. Do I need to PR each module separately?

Please do that.

**Comment by JJ** [comment]
It's not only that, there're a number of dependencies that are not found, like 
```
[Pakku] Could not find Log::Async in:
```

If you want, I can edit this PR to leave only Pakku::Spec and then you can create separate PRs for the rest.

**Comment by hythm7** [comment]
> If you want, I can edit this PR to leave only Pakku::Spec and then you can create separate PRs for the rest.

yes please do that. Thanks

**Comment by hythm7** [comment]
Thanks @JJ  for fixing and merging this PR. I suppose I should not submit the remaining modules now and need to wait 
 untill `Pakku::Spec` is seen by `zef`?

**Comment by JJ** [comment]
It shouldn't take more than a couple of hours, that's the usual period for updating. Wait for one hour, just to be on the safe side, or check locally with zef search until it shows up.

**Pull request merged**
