### PR TITLE
Add Intl::Format::Number to ecosystem

### PR DESCRIPTION
**Pull request by alabamenhu**
(can we get it on the first try this time?)

- [X] I **agree** to the usage of the META file as listed [here](https://github.com/Raku/ecosystem#legal).

- [X] I have a license field listed in my META file that is one of https://spdx.org/licenses
  - [ ] My license is not one of those found on spdx.org but I **do** have a license field.
        In this case make sure you have a license URL listed under support. [See this example](https://github.com/samcv/URL-Find/blob/master/META6.json).
   - [ ] I **don't** have a license field. Yes, I understand this is **not recommended**.

### CODE REVIEW

**Comment by JJ** [comment]
What's happened to the tests?

**Comment by JJ** [comment]
So we have no tests for the time being... Let's see how we solve this.

**Comment by alabamenhu** [comment]
> What's happened to the tests?

I'm not sure, is something up with Travis?  The checks tab is currently hanging (saying "Waiting for checks information").  Not sure what's going on there — but when I  made the PR, it never showed the tests as starting like it normally does.

**Comment by JJ** [comment]
Yep, Travis credit is gone

**Comment by JJ** [comment]
Should have merged this first. Anyway, I'll fix tomorrow

**Comment by jonathanstowe** [comment]
Hi,
I've manually de-conflicted this and pushed.  Please check that I get the intent correct.

**Pull request merged**
